# Задаём имя проекта
name: htmx-books-test

services:
  web:
    # Указываем директорию ./app, в которой содержится Dockerfile для сборки образа
    build: ./app
    # Запускаем встроенный сервер Django
    command: python manage.py runserver 0.0.0.0:8000
    # Пробрасываем 8000 порт контейнера на 8000 порт локалхоста(127.0.0.1:8000)
    ports:
      - 127.0.0.1:8000:8000
    # Файл содержащий переменные окружения для контейнера
    env_file:
      - .env